//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicalSimulations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MechanicalSimulations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap BitmapButterfly {
            get {
                object obj = ResourceManager.GetObject("BitmapButterfly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapCardiod {
            get {
                object obj = ResourceManager.GetObject("BitmapCardiod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapChaoticPendelum {
            get {
                object obj = ResourceManager.GetObject("BitmapChaoticPendelum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapCircle {
            get {
                object obj = ResourceManager.GetObject("BitmapCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapDanglingStick {
            get {
                object obj = ResourceManager.GetObject("BitmapDanglingStick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapDoublePendelum {
            get {
                object obj = ResourceManager.GetObject("BitmapDoublePendelum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapDoubleSpring {
            get {
                object obj = ResourceManager.GetObject("BitmapDoubleSpring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapDoubleSpring2D {
            get {
                object obj = ResourceManager.GetObject("BitmapDoubleSpring2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapHump {
            get {
                object obj = ResourceManager.GetObject("BitmapHump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapOval {
            get {
                object obj = ResourceManager.GetObject("BitmapOval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapPendelumCart {
            get {
                object obj = ResourceManager.GetObject("BitmapPendelumCart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapRollerCoaster {
            get {
                object obj = ResourceManager.GetObject("BitmapRollerCoaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapRollerSpring {
            get {
                object obj = ResourceManager.GetObject("BitmapRollerSpring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapSimpleCollision {
            get {
                object obj = ResourceManager.GetObject("BitmapSimpleCollision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapSingleSpring {
            get {
                object obj = ResourceManager.GetObject("BitmapSingleSpring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapSingleSpring2D {
            get {
                object obj = ResourceManager.GetObject("BitmapSingleSpring2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapSingleSpring2D1 {
            get {
                object obj = ResourceManager.GetObject("BitmapSingleSpring2D1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapSpiral {
            get {
                object obj = ResourceManager.GetObject("BitmapSpiral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapTwoOverHeadSp {
            get {
                object obj = ResourceManager.GetObject("BitmapTwoOverHeadSp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BitmapTwoRollers {
            get {
                object obj = ResourceManager.GetObject("BitmapTwoRollers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BittmapInfinity {
            get {
                object obj = ResourceManager.GetObject("BittmapInfinity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconMechanic {
            get {
                object obj = ResourceManager.GetObject("IconMechanic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pic_molecule6 {
            get {
                object obj = ResourceManager.GetObject("pic_molecule6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rope {
            get {
                object obj = ResourceManager.GetObject("Rope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon SpringIcon {
            get {
                object obj = ResourceManager.GetObject("SpringIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
